<h1>M2 Assessment</h1>
<p><strong>Assess how dietary intake and nutritional health are influenced by dietary habits and lifestyle choices</strong></p>
<p>I will answer each part clearly for Christos and Mary using the same layout.</p>

<h2>Christos</h2>

<h3>1. What dietary habits and lifestyle choices might he have?</h3>
<p>Christos is 70, lives alone in a village with restricted public transport, and only has a convenience store nearby. He does not enjoy cooking, so he is likely to choose quick and simple foods that take little effort. He may rely on ready meals, tinned foods, packaged snacks, and basic items like bread because they are easy to buy and prepare. Living alone can also reduce motivation to cook proper meals, so he might skip meals, eat smaller portions, or eat the same foods repeatedly. Since he has Type 2 diabetes, he may try to avoid obvious sugary foods, but convenience options can still contain lots of hidden sugar and refined carbohydrates. Because of his age, he may also be less physically active, which makes it easier to gain weight and harder to manage blood glucose levels.</p>

<h3>2. Based on these factors, what foods might he eat too much or too little of?</h3>
<p>Christos might eat too much of refined carbohydrates, such as white bread, biscuits, pastries, and sugary snacks, because they are common in convenience stores and require no cooking. He might also eat too much processed food, which is often high in salt and saturated fat, because it is quick and feels convenient when he does not want to cook. At the same time, he might eat too little fresh fruit and vegetables because they can be less available, more expensive, and spoil faster. He might also eat too little fibre, wholegrains, and lean protein, especially if he is not preparing meals from scratch.</p>

<h3>3. What specific nutrients might he have too much or too little of?</h3>
<p>Christos may have too much sugar in his diet, which can raise his blood glucose and make diabetes harder to manage. He may also have too much sodium, because many ready meals, tinned foods, and snacks are high in salt. He could also have too much saturated fat, which can raise cholesterol and increase cardiovascular risk. He may have too little fibre, which is important for digestion and helps slow the absorption of glucose. He may have too little protein, which matters more in older age because it helps maintain muscle mass and strength. He could also have low vitamin D, which is common in older adults and affects bone health, especially if he spends less time outdoors.</p>

<h3>4. What might be the impact on his health?</h3>
<p>If Christos regularly eats foods high in sugar and refined carbohydrates, his blood glucose may stay high and unstable, which increases the risk of long term diabetes complications like heart disease, kidney damage, and nerve problems. If his salt intake is high, his blood pressure may rise, which increases the risk of stroke and heart problems. If he does not eat enough protein, he may lose muscle and become frailer, which makes falls more likely and recovery harder. On the positive side, if he chooses more wholegrain carbohydrates, more vegetables, and steady sources of lean protein, it could help control blood sugar and support heart health. If he uses simple healthier cooking methods like grilling or oven baking, it could reduce fat intake without making cooking feel too difficult.</p>

<h3>5. Assess an alternative method of feeding and its impact</h3>
<p>An alternative method of feeding for Christos could be prescribed oral nutritional supplements if he became undernourished or started losing weight. These supplements can increase calorie and protein intake, which could help him maintain muscle and energy levels. This could reduce frailty and support his overall strength and recovery if he becomes unwell. However, because he has Type 2 diabetes, supplements would need to be chosen carefully since some contain high amounts of sugar. If the wrong type is used, it could raise his blood glucose and worsen diabetes control, so this option should only be used with medical advice and monitoring.</p>

<h2>Mary</h2>

<h3>1. What dietary habits and lifestyle choices might she have?</h3>
<p>Mary is 27, pregnant, vegetarian, lactose intolerant, and a single mum living on benefits. Pregnancy increases her need for key nutrients because her body is supporting a growing baby. Being vegetarian means she does not eat meat or fish, so she has to plan her protein and iron sources more carefully. Lactose intolerance means she cannot rely on standard dairy for calcium, so she needs alternatives like fortified plant milks or other calcium rich foods. Because she is on a low income and raising a toddler, she may be more likely to choose foods that are cheap, quick, and filling, and she might not always have time or energy to cook balanced meals from scratch.</p>

<h3>2. Based on these factors, what foods might she eat too much or too little of?</h3>
<p>Mary might eat too much processed vegetarian food, such as meat substitutes, oven foods, or ready meals, because they can be convenient and require little prep. She might also eat too much refined carbohydrate, like white pasta, white bread, and snack foods, especially if they are cheaper and more available. She might eat too little iron rich food, calcium rich food, and nutrient dense protein sources if her meals are not well planned. She might also eat too little fresh fruit and vegetables if cost and time make it harder to buy and prepare them regularly.</p>

<h3>3. What specific nutrients might she have too much or too little of?</h3>
<p>Mary may have too much sugar and saturated fat if she relies on processed foods and snacks, even if the foods are vegetarian. She may have too little iron, which is especially important during pregnancy, and plant based iron is harder for the body to absorb than iron from meat. She may have too little vitamin B12, because it is mostly found in animal products, and a lack of B12 can affect energy and nerve function. She may have too little calcium because she cannot have normal dairy, and calcium is needed for the baby’s bones and to protect her own bone stores. She may also have too little protein if she does not regularly include beans, lentils, eggs, tofu, or nuts. She might also be at risk of low folic acid if she is not taking the recommended pregnancy supplement, even if she eats some folate containing foods.</p>

<h3>4. What might be the impact on her health?</h3>
<p>If Mary does not get enough iron, she could develop iron deficiency anaemia, which can cause tiredness, weakness, and poor concentration, and that would make parenting and pregnancy harder. Low iron during pregnancy can also increase the risk of low birth weight and other complications. If her B12 intake is low, it can affect her nervous system and, in pregnancy, it can affect the baby’s development. If calcium intake is low, the baby may still take what it needs, but it can increase the risk of Mary losing bone density over time. If she eats too many high sugar and high fat foods, she may gain excessive weight during pregnancy, which increases the risk of gestational diabetes and high blood pressure. On the positive side, if she plans a balanced vegetarian diet with beans, lentils, wholegrains, vegetables, fruit, and fortified dairy alternatives, she can meet her needs well. If she takes recommended supplements like folic acid, it can reduce the risk of serious problems in early development.</p>

<h3>5. Assess an alternative method of feeding and its impact</h3>
<p>An alternative feeding method for Mary after birth is breastfeeding. Breastfeeding provides appropriate nutrition for the baby and supports the baby’s immune system, which can reduce infections in early life. It can also support bonding and may be cheaper than formula feeding, which could matter because she is on benefits. However, breastfeeding increases the mother’s nutritional needs, so Mary would need enough calories, protein, fluids, and key nutrients. If she is already low in iron or B12, she might feel more exhausted and struggle to recover after birth, so she would need support with diet planning, fortified foods, and supplements if advised by a health professional.</p>
